version: "3.1"
services:
  cassandra:
    image: cassandra
    ports:
      - '9042:9042'
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - /Users/deepaknataraj/Downloads/targetProject/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring: