spring:
  data:
    cassandra:
      contact-points: ["host.docker.internal"]
      port: 9042
      local-datacenter: datacenter1
api:
  product:
    baseurl:  https://redsky.target.com
    url : /v2/pdp/tcin/{productId}
    connectionTimeOut: 1000
    readTimeOut: 4000
    keepAlive : true

management:
  endpoints:
    web:
      exposure:
        include: "*"

